/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
export namespace Components {
    interface AppEmpfehlungen {
        "test": string;
    }
    interface AppHome {
    }
    interface AppOutfitvorschlaege {
        "test": string;
    }
    interface AppProduktbewertung {
        "test": string;
    }
    interface AppProduktseite {
        "test": string;
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppUebersicht {
        "test": string;
    }
    interface MenueFooter {
    }
    interface ProduktVorschau {
        "benennung": string;
        "bild": string;
        "kurztext": string;
    }
}
declare global {
    interface HTMLAppEmpfehlungenElement extends Components.AppEmpfehlungen, HTMLStencilElement {
    }
    var HTMLAppEmpfehlungenElement: {
        prototype: HTMLAppEmpfehlungenElement;
        new (): HTMLAppEmpfehlungenElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppOutfitvorschlaegeElement extends Components.AppOutfitvorschlaege, HTMLStencilElement {
    }
    var HTMLAppOutfitvorschlaegeElement: {
        prototype: HTMLAppOutfitvorschlaegeElement;
        new (): HTMLAppOutfitvorschlaegeElement;
    };
    interface HTMLAppProduktbewertungElement extends Components.AppProduktbewertung, HTMLStencilElement {
    }
    var HTMLAppProduktbewertungElement: {
        prototype: HTMLAppProduktbewertungElement;
        new (): HTMLAppProduktbewertungElement;
    };
    interface HTMLAppProduktseiteElement extends Components.AppProduktseite, HTMLStencilElement {
    }
    var HTMLAppProduktseiteElement: {
        prototype: HTMLAppProduktseiteElement;
        new (): HTMLAppProduktseiteElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppUebersichtElement extends Components.AppUebersicht, HTMLStencilElement {
    }
    var HTMLAppUebersichtElement: {
        prototype: HTMLAppUebersichtElement;
        new (): HTMLAppUebersichtElement;
    };
    interface HTMLMenueFooterElement extends Components.MenueFooter, HTMLStencilElement {
    }
    var HTMLMenueFooterElement: {
        prototype: HTMLMenueFooterElement;
        new (): HTMLMenueFooterElement;
    };
    interface HTMLProduktVorschauElement extends Components.ProduktVorschau, HTMLStencilElement {
    }
    var HTMLProduktVorschauElement: {
        prototype: HTMLProduktVorschauElement;
        new (): HTMLProduktVorschauElement;
    };
    interface HTMLElementTagNameMap {
        "app-empfehlungen": HTMLAppEmpfehlungenElement;
        "app-home": HTMLAppHomeElement;
        "app-outfitvorschlaege": HTMLAppOutfitvorschlaegeElement;
        "app-produktbewertung": HTMLAppProduktbewertungElement;
        "app-produktseite": HTMLAppProduktseiteElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-uebersicht": HTMLAppUebersichtElement;
        "menue-footer": HTMLMenueFooterElement;
        "produkt-vorschau": HTMLProduktVorschauElement;
    }
}
declare namespace LocalJSX {
    interface AppEmpfehlungen {
        "test"?: string;
    }
    interface AppHome {
    }
    interface AppOutfitvorschlaege {
        "test"?: string;
    }
    interface AppProduktbewertung {
        "test"?: string;
    }
    interface AppProduktseite {
        "test"?: string;
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppUebersicht {
        "test"?: string;
    }
    interface MenueFooter {
    }
    interface ProduktVorschau {
        "benennung"?: string;
        "bild"?: string;
        "kurztext"?: string;
    }
    interface IntrinsicElements {
        "app-empfehlungen": AppEmpfehlungen;
        "app-home": AppHome;
        "app-outfitvorschlaege": AppOutfitvorschlaege;
        "app-produktbewertung": AppProduktbewertung;
        "app-produktseite": AppProduktseite;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-uebersicht": AppUebersicht;
        "menue-footer": MenueFooter;
        "produkt-vorschau": ProduktVorschau;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-empfehlungen": LocalJSX.AppEmpfehlungen & JSXBase.HTMLAttributes<HTMLAppEmpfehlungenElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-outfitvorschlaege": LocalJSX.AppOutfitvorschlaege & JSXBase.HTMLAttributes<HTMLAppOutfitvorschlaegeElement>;
            "app-produktbewertung": LocalJSX.AppProduktbewertung & JSXBase.HTMLAttributes<HTMLAppProduktbewertungElement>;
            "app-produktseite": LocalJSX.AppProduktseite & JSXBase.HTMLAttributes<HTMLAppProduktseiteElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-uebersicht": LocalJSX.AppUebersicht & JSXBase.HTMLAttributes<HTMLAppUebersichtElement>;
            "menue-footer": LocalJSX.MenueFooter & JSXBase.HTMLAttributes<HTMLMenueFooterElement>;
            "produkt-vorschau": LocalJSX.ProduktVorschau & JSXBase.HTMLAttributes<HTMLProduktVorschauElement>;
        }
    }
}
